# Site settings
title: Ariana's Website
description: Personal Website of Ariana Moncada
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ariana Moncada
user_description: Currently I am a Masters of Data Science Graduate student at the University of San Francisco. Prior to joining USF, I was an undergraduate Research Assistant in a Solar Forecasting Lab at The Texas Sustainable Energy Research Institute. Some of my interests include Computer Vision, Machine Learning, Time Series and Geospatial Analysis applied to various domains including renewable energy, utilties, and IoT sensing.
user_title: Data Scientist
email: arianam.moncada@gmail.com
twitter_username: 
github_username:  arianamoncada
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
